#!/usr/bin/env bash

# Define the fixed path to the scripts on GitHub
SCRIPT_URL="https://github.com/jennyo88/scripts/raw/main/books/overdrive"

# Function to fetch and run the fixed script from GitHub
fetch_and_run_fixed_script() {
  local script_url=$1
  local audiobook_file=$2

  # Fetch the fixed script
  wget -q -O "overdrive" "$script_url"

  # Check if the script was fetched successfully
  if [ $? -eq 0 ]; then
    echo "Running fixed script: overdrive"
    # Run the fetched script with provided audiobook file name as argument
    bash "overdrive" download "$audiobook_file"
    # Remove the fetched script
    rm "overdrive"
  else
    echo "Failed to fetch script: $script_url"
  fi
}

# Run the fixed script with the provided audiobook file name
fetch_and_run_fixed_script "$SCRIPT_URL" "$audiobook_file"

# List directories in the current directory
echo "List of directories in the current directory:"
directories=($(find . -maxdepth 1 -type d | sed 's|./||'))
for ((i=0; i<${#directories[@]}; i++)); do
  echo "$i. ${directories[$i]}"
done

# Prompt user to choose the directory number
read -p "Enter the number corresponding the book you want to bind: " selected_index

# Validate user input
if [[ $selected_index =~ ^[0-9]+$ && $selected_index -ge 0 && $selected_index -lt ${#directories[@]} ]]; then
  selected_directory="${directories[$selected_index]}"
  echo "Selected folder: $selected_directory"

  # Modify the folder name to the desired format
  new_folder_name=$(echo "$selected_directory" | awk '{print toupper(substr($1,1,1))substr($1,2)"_"toupper(substr($2,1,1))substr($2,2)}' | sed 's/ //g')

  # Rename the folder to the new format
  mv "$selected_directory" "$new_folder_name"
  echo "Folder renamed to: $new_folder_name"

  pybind -d "$new_folder_name"
else
  echo "Invalid selection. Exiting..."
fi
