#!/bin/bash

# Define the GitHub repository URL
repo_url="https://github.com/username/repository"

# Function to fetch and run a script from GitHub
fetch_and_run_script() {
    local script_name=$1
    local arg1=$2
    local script_url="${repo_url}/raw/main/${script_name}"

    # Fetch the script
    wget -q -O "$script_name" "$script_url"

    # Check if the script was fetched successfully
    if [ $? -eq 0 ]; then
        echo "Running script: $script_name"
        # Run the fetched script with provided argument
        bash "$script_name" "$arg1"
        # Remove the fetched script
        rm "$script_name"
    else
        echo "Failed to fetch script: $script_url"
    fi
}

# Prompt user to enter the audiobook file name
read -p "Enter name of the audiobook file: " audiobook_file

# Run the overdrive script with the provided audiobook file name
fetch_and_run_script "overdrive" "$audiobook_file"


# Function to transform the folder name
transform_folder_name() {
    local old_name="$1"
    # Replace spaces with underscores and capitalize letters after spaces
    new_name=$(echo "$old_name" | sed -r 's/([[:space:]]+)([[:alpha:]])/\U\2/g; s/[[:space:]]+/_/g')
    echo "$new_name"
}

# List directories in the current directory
echo "List of directories in current directory:"
ls -d */

# Prompt user to choose the folder name
read -p "Enter name of the book to bin: " overdrive_folder

# Transform the folder name
transformed_folder=$(transform_folder_name "$overdrive_folder")

# Run the pybind program with the transformed folder name
echo "Running pybind with folder: $transformed_folder"
pybind -d "$transformed_folder"
