#!/usr/bin/env bash

# Convert
# Author: Jennifer Romero
# Description: This script provides a menu-driven interface to convert files
# Version: 4.0
# Last Updated: Feb 24, 2024
# GitHub Repository: https://github.com/jennyo88/scripts

# -----------------------------------
# COLORS
# -----------------------------------

load_colors() {
	BLUE=$'\e[38;5;39m'	    	# Blue color
	ORANGE=$'\e[38;5;208m'	# Orange color
	RED=$'\e[1;31m'		# Red color (bold)
	RESET=$'\e[0m'		# Reset color attributes
}

# Calling the load_colors() function to set color variables
load_colors # Only loaded once



# -----------------------------------
# INFINITE LOOP
# -----------------------------------

while true
do
	show_banner_0 && show_menu_${main_menu}
done
