#!/usr/bin/env bash

# Function to execute a remote script
execute_remote_script() {
    local script_url=$1
    echo "Executing script: $script_url"
    # Replace the following line with the command to execute your remote script
    # Example: bash -c "$(curl -fsSL $script_url)"
}

# Function to download and execute a bash script
execute_bash_script() {
    read -p "Enter the URL of the Bash script: " bash_script_url
    echo "Downloading and executing Bash script from: $bash_script_url"
    
    # Download and execute the remote script using bash -c
    if bash -c "$(curl -fsSL $bash_script_url)"; then
        echo "Script execution successful."
    else
        echo "Script execution failed."
    fi
}

# Function to execute a Python script
execute_python_script() {
    # Specify the Python script URL
    local python_script_url="https://raw.githubusercontent.com/jennyo88/scripts/main/scripts/tes_py"
    
    echo "Executing Python script from: $python_script_url"
    
    # Replace the following line with the command to execute your Python script
    # Example: bash -c "$(curl -fsSL $python_script_url)"
    if bash -c "$(curl -fsSL $python_script_url)"; then
        echo "Script execution successful."
    else
        echo "Script execution failed."
    fi
}

# Function to display and handle the main menu
main_menu() {
    clear
    echo "==================== MAIN MENU ===================="
    echo "Press Ctrl+C to exit at any time."
    echo ""
    echo " 1. Jennyo88 Scripts Menu"
    echo " 2. Other Scripts Menu"
    echo ""
    echo " 0. Exit"
    echo "==================================================="

    read -p "Enter your choice (0-2): " choice

    case $choice in
        1) jennyo88_scripts_menu ;;
        2) other_scripts_menu ;;
        0) echo "Exiting..."; exit 0 ;;
        *) echo "Invalid choice. Please enter a number between 0 and 2." ;;
    esac
}

# Function to display and handle the other scripts menu
other_scripts_menu() {
    clear
    echo "================ OTHER SCRIPTS MENU ================"
    echo "Press Ctrl+C to go back to the main menu."
    echo ""
    echo " 1. Execute Other Bash Script"
    echo " 2. Execute Python Script"
    echo ""
    echo " 0. Go back to Main Menu"
    echo "======================================================="

    read -p "Enter your choice (0-2): " choice

    case $choice in
        1) execute_bash_script ;;
        2) execute_python_script ;;
        0) main_menu ;;
        *) echo "Invalid choice. Please enter a number between 0 and 2." ;;
    esac
}

# Start with the main menu
main_menu
